# Generated by Django 4.2 on 2025-11-27 11:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_order_id', models.CharField(db_index=True, help_text='Unique merchant order ID', max_length=255, unique=True)),
                ('phonepe_transaction_id', models.CharField(blank=True, db_index=True, help_text='PhonePe transaction ID', max_length=255, null=True)),
                ('object_id', models.CharField(db_index=True, help_text='The ID of the related object', max_length=255)),
                ('transaction_type', models.CharField(choices=[('PRODUCT_PURCHASE', 'Product Purchase'), ('CASE_ENTRY_FEE', 'Case Entry Fee'), ('SUBSCRIPTION', 'Subscription'), ('SERVICE_FEE', 'Service Fee'), ('BOOKING', 'Booking'), ('CONSULTATION', 'Consultation Fee'), ('OTHER', 'Other')], db_index=True, help_text='Type of transaction', max_length=30)),
                ('user_identifier', models.CharField(db_index=True, help_text='User ID or identifier for tracking', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in INR', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], db_index=True, default='INITIATED', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Detailed status message')),
                ('payment_method_type', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet')], max_length=20, null=True)),
                ('payment_method', models.JSONField(blank=True, help_text='Detailed payment method information', null=True)),
                ('redirect_url', models.URLField(help_text='Redirect URL after payment')),
                ('callback_url', models.URLField(blank=True, help_text='Webhook callback URL', null=True)),
                ('udf1', models.CharField(blank=True, help_text='User defined field 1', max_length=255)),
                ('udf2', models.CharField(blank=True, help_text='User defined field 2', max_length=255)),
                ('udf3', models.CharField(blank=True, help_text='User defined field 3', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as key-value pairs')),
                ('webhook_response', models.JSONField(blank=True, help_text='Full webhook response from payment gateway', null=True)),
                ('gateway_response_code', models.CharField(blank=True, max_length=50)),
                ('gateway_response_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum retry attempts allowed')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount refunded', max_digits=10)),
                ('refund_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('refund_completed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reference_id', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(blank=True, help_text='Checksum for data integrity verification', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Transaction expiry time', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(help_text='The model this transaction is related to (Product, CaseEntry, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['merchant_order_id'], name='gateway_pay_merchan_f0f4c8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['phonepe_transaction_id'], name='gateway_pay_phonepe_0fe586_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='gateway_pay_status_9a58ad_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user_identifier', 'status'], name='gateway_pay_user_id_3a5f15_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['is_active', 'status'], name='gateway_pay_is_acti_998b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['-created_at'], name='gateway_pay_created_b81ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['content_type', 'object_id'], name='gateway_pay_content_3c2795_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_type', 'status'], name='gateway_pay_transac_8f6fc7_idx'),
        ),
    ]
