# Generated by Django 4.2 on 2025-11-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method_type',
            field=models.CharField(blank=True, choices=[('online', 'Online Payment'), ('milk_bill', 'Milk Bill Payment')], max_length=20, null=True),
        ),
    ]
