# Generated by Django 4.2 on 2024-11-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberHierarchyView',
            fields=[
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
                ('plant_code', models.CharField(blank=True, max_length=50, null=True)),
                ('mcc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bmc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('mpp_code', models.CharField(blank=True, max_length=50, null=True)),
                ('member_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('member_tr_code', models.CharField(blank=True, max_length=50, null=True)),
                ('member_name', models.CharField(blank=True, max_length=255, null=True)),
                ('member_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('member_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('member_type', models.CharField(blank=True, max_length=50, null=True)),
                ('caste_category', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('wef_date', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('folio_no', models.CharField(blank=True, max_length=50, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('application_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('member_master_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('ex_member_code', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Member Heirarchy',
                'verbose_name_plural': 'Member Heirarchies',
                'db_table': 'member_hierarchy_view',
                'managed': False,
            },
        ),
    ]
