# Generated by Django 4.2 on 2025-06-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0004_v_pouredmembersummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitatorDashboardSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpp_code', models.CharField(blank=True, max_length=50, null=True)),
                ('collection_date', models.CharField(blank=True, null=True)),
                ('shift_code', models.CharField(blank=True, max_length=10, null=True)),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_snf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('composite_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('composite_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('composite_snf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('composite_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_efu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('composite_efu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('composite_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rate_per_efu_composite', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('adjusted_actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Facilitator Dashboard Summary',
                'verbose_name_plural': 'Facilitator Dashboard Summaries',
                'db_table': 'dashboard_summary_cache',
                'managed': False,
            },
        ),
    ]
