# Generated by Django 4.2 on 2025-06-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0005_facilitatordashboardsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addressbook',
        ),
        migrations.DeleteModel(
            name='AddressbookPortal',
        ),
        migrations.DeleteModel(
            name='Adulteration',
        ),
        migrations.DeleteModel(
            name='AdulterationHistory',
        ),
        migrations.DeleteModel(
            name='AdulterationResult',
        ),
        migrations.DeleteModel(
            name='AdulterationResultHistory',
        ),
        migrations.DeleteModel(
            name='AdulterationTxn',
        ),
        migrations.DeleteModel(
            name='AdulterationTxnHistory',
        ),
        migrations.DeleteModel(
            name='AgeingType',
        ),
        migrations.DeleteModel(
            name='AgeingTypeHistory',
        ),
        migrations.DeleteModel(
            name='AggregationUnlock',
        ),
        migrations.DeleteModel(
            name='TblUserLogin',
        ),
    ]
