# Generated by Django 4.2 on 2025-08-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0006_delete_addressbook_delete_addressbookportal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHierarchySnapshot',
            fields=[
                ('company_code', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=50)),
                ('plant_code', models.CharField(max_length=10)),
                ('plant_tr_code', models.CharField(max_length=50)),
                ('plant_name', models.CharField(max_length=255)),
                ('mcc_code', models.CharField(max_length=10)),
                ('mcc_tr_code', models.CharField(max_length=50)),
                ('mcc_name', models.CharField(max_length=255)),
                ('bmc_code', models.CharField(max_length=10)),
                ('bmc_tr_code', models.CharField(max_length=50)),
                ('bmc_name', models.CharField(max_length=255)),
                ('mpp_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mpp_ex_code', models.CharField(max_length=50)),
                ('mpp_tr_code', models.CharField(max_length=50)),
                ('mpp_name', models.CharField(max_length=255)),
                ('mpp_type', models.CharField(max_length=50)),
                ('route_code', models.CharField(max_length=10)),
                ('route_ex_code', models.CharField(max_length=50)),
                ('route_name', models.CharField(max_length=255)),
                ('wef_date', models.DateField()),
                ('is_default', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('dpu_station_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Business Hierarchy Snapshot',
                'verbose_name_plural': 'Business Hierarchy Snapshots',
                'db_table': 'business_hierarchy_snapshot',
                'managed': False,
            },
        ),
    ]
