# Generated by Django 5.0 on 2024-06-05 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created AT'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=6, verbose_name='OTP'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to=settings.AUTH_USER_MODEL, verbose_name='उपभोक्ता'),
        ),
    ]
