# Generated by Django 4.2 on 2024-08-29 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SahayakIncentives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='MCC Code')),
                ('mcc_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='MCC Name')),
                ('mpp_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='MPP Code')),
                ('mpp_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='MPP Name')),
                ('month', models.CharField(max_length=100, verbose_name='Month')),
                ('opening', models.FloatField(default=0.0, verbose_name='Previous Month Opening')),
                ('milk_incentive', models.FloatField(default=0.0, verbose_name='Milk Incentive')),
                ('other_incentive', models.FloatField(default=0.0, verbose_name='Other Incentive')),
                ('closing', models.FloatField(default=0.0, verbose_name='Closing')),
                ('payable', models.FloatField(default=0.0, verbose_name='Net Payable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to=settings.AUTH_USER_MODEL, verbose_name='Sahayak')),
            ],
            options={
                'verbose_name': 'Product Rate',
                'verbose_name_plural': 'Product Rates',
                'db_table': 'sahayak',
            },
        ),
        migrations.CreateModel(
            name='ProductRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of product', max_length=100, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Rate of the product', max_digits=10, verbose_name='Product Price')),
                ('image', models.ImageField(blank=True, help_text='Image of the product to display as icon, size should be 100x100', null=True, upload_to='products/', verbose_name='Product Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Product Rate',
                'verbose_name_plural': 'Product Rates',
                'db_table': 'product_rate',
            },
        ),
    ]
