# Generated by Django 5.0 on 2024-06-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_code', models.CharField(max_length=50, verbose_name='Product Code')),
                ('image', models.ImageField(upload_to='brand_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Image',
                'verbose_name_plural': 'Brand Images',
                'db_table': 'brand_image',
            },
        ),
    ]
