# Generated by Django 4.2 on 2024-09-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_productrate_locale_productrate_name_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrate',
            name='price_description',
            field=models.CharField(blank=True, help_text='Description of the product price, e.g., price of 1 bag or 1 pill', max_length=255, null=True, verbose_name='Price Description'),
        ),
    ]
