# Generated by Django 5.0 on 2024-06-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_brandimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandimage',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='brandimage',
            name='brand_code',
            field=models.CharField(max_length=50, verbose_name='Brand Code'),
        ),
    ]
