# Generated by Django 4.2 on 2024-11-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_productrate_price_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sahayakincentives',
            options={'verbose_name': 'Sahayak Incentive', 'verbose_name_plural': 'Sahayak Incentives'},
        ),
        migrations.AddField(
            model_name='userdevice',
            name='mpp_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MPP Code'),
        ),
    ]
