# Generated by Django 4.2 on 2024-11-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_sahayakincentives_options_userdevice_mpp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='module',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Module Code'),
        ),
    ]
