# Generated by Django 5.0 on 2024-06-24 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_categoryimage_alter_brandimage_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockOpening',
            fields=[
                ('product_stock_opening_code', models.AutoField(primary_key=True, serialize=False)),
                ('financial_year_code', models.IntegerField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=50, verbose_name='Product Code')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Name')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('as_on_date', models.DateTimeField(blank=True, null=True)),
                ('warehouse_code', models.IntegerField(blank=True, null=True, verbose_name='Warehouse Code')),
                ('warehouse_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Warehouse Name')),
                ('bin_location_code', models.IntegerField(blank=True, null=True, verbose_name='Bin Location Code')),
                ('bin_location_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bin Location Name')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_user_stock', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_user_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Stock Opening',
                'verbose_name_plural': 'Product Stock Opening',
                'db_table': 'product_stock_opening',
            },
        ),
    ]
