# Generated by Django 4.2 on 2024-11-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_userdevice_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahayakincentives',
            name='recovery_deposit',
            field=models.FloatField(default=0.0, verbose_name='Recovery Deposit'),
        ),
        migrations.AddField(
            model_name='sahayakincentives',
            name='sahayak_recovery',
            field=models.FloatField(default=0.0, verbose_name='Sahayak Recovery'),
        ),
    ]
