# Generated by Django 4.2 on 2024-11-18 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0008_sahayakincentives_additional_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SahayakFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('mpp_code', models.CharField(blank=True, max_length=9, null=True, verbose_name='MPP Code')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('re opened', 'Re-opened')], default='open', max_length=100, verbose_name='Feedback Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resolved_at', models.DateTimeField(verbose_name='Resolved At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('message', models.TextField(verbose_name='Message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sahayak Feedback',
                'verbose_name_plural': 'Sahayak Feedbacks',
                'db_table': 'sahayak_feedback',
            },
        ),
        migrations.CreateModel(
            name='FeedbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='member.sahayakfeedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Log',
                'verbose_name_plural': 'Feedback Logs',
                'db_table': 'feedback_logs',
            },
        ),
    ]
