# Generated by Django 4.2 on 2024-11-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_sahayakfeedback_feedbacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahayakfeedback',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='feedback_files/', verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='sahayakfeedback',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolved At'),
        ),
    ]
