# Generated by Django 4.2 on 2024-11-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_news_remove_sahayakincentives_recovery_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Check this box to mark the article as read.', verbose_name='Is Read'),
        ),
        migrations.AddField(
            model_name='sahayakincentives',
            name='year',
            field=models.CharField(default='2024', max_length=100, verbose_name='Year'),
        ),
    ]
