# Generated by Django 4.2 on 2024-11-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_news_is_read_sahayakincentives_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahayakincentives',
            name='tds',
            field=models.FloatField(default=0.0, verbose_name='TDS'),
        ),
    ]
