# Generated by Django 4.2 on 2024-11-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_sahayakincentives_tds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sahayakincentives',
            name='sahayak_recovery',
        ),
        migrations.AddField(
            model_name='sahayakincentives',
            name='asset_recovery',
            field=models.FloatField(default=0.0, verbose_name='Asset Recovery'),
        ),
        migrations.AddField(
            model_name='sahayakincentives',
            name='cda_recovery',
            field=models.FloatField(default=0.0, verbose_name='C.D.A Recovery'),
        ),
        migrations.AddField(
            model_name='sahayakincentives',
            name='cf_incentive',
            field=models.FloatField(default=0.0, verbose_name='Cattle Feed Incentive'),
        ),
        migrations.AddField(
            model_name='sahayakincentives',
            name='milk_qty',
            field=models.FloatField(default=0.0, verbose_name='Milk Qty'),
        ),
        migrations.AddField(
            model_name='sahayakincentives',
            name='mm_incentive',
            field=models.FloatField(default=0.0, verbose_name='Mineral Mixture Incentive'),
        ),
        migrations.AddField(
            model_name='sahayakincentives',
            name='tds_amt',
            field=models.FloatField(default=0.0, verbose_name='TDS (AMT)'),
        ),
        migrations.AlterField(
            model_name='sahayakincentives',
            name='closing',
            field=models.FloatField(default=0.0, verbose_name='Closing Balance'),
        ),
        migrations.AlterField(
            model_name='sahayakincentives',
            name='opening',
            field=models.FloatField(default=0.0, verbose_name='Opening Balance'),
        ),
        migrations.AlterField(
            model_name='sahayakincentives',
            name='payable',
            field=models.FloatField(default=0.0, verbose_name='Payable'),
        ),
        migrations.AlterField(
            model_name='sahayakincentives',
            name='tds',
            field=models.FloatField(default=0.0, verbose_name='TDS(%)'),
        ),
    ]
