# Generated by Django 4.2 on 2025-01-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_remove_sahayakincentives_sahayak_recovery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahayakincentives',
            name='milk_incentive',
            field=models.FloatField(default=0.0, verbose_name='Milk Incentive'),
        ),
    ]
