# Generated by Django 4.2 on 2025-05-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_alter_sahayakincentives_milk_incentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='fcm_token',
            field=models.TextField(blank=True, null=True, verbose_name='FCM Token'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
