# Generated by Django 4.2 on 2025-08-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_userdevice_fcm_token_userdevice_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='device_type',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=10),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
