# Generated by Django 4.2 on 2025-10-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_userdevice_device_type_userdevice_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='module',
            field=models.CharField(default='member', help_text='Module Specific News. For ex:- member, facilitator, sahayak', max_length=255, verbose_name='Module'),
        ),
    ]
