# Generated by Django 4.2 on 2025-11-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_rewardedadtransaction_rewardwithdrawalrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahayakincentives',
            name='recovery_deposited',
            field=models.FloatField(default=0.0, verbose_name='Recovery Deposited'),
        ),
        migrations.AddField(
            model_name='sahayakincentives',
            name='transporter_recovery',
            field=models.FloatField(default=0.0, verbose_name='Transporter Recovery'),
        ),
    ]
