# Generated by Django 4.2 on 2025-11-25 09:09

import django.core.validators
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_sahayakincentives_recovery_deposited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacklog',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedbacklog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sahayakfeedback',
            name='sender',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date'], 'permissions': [('can_feature_news', 'Can mark news as featured'), ('can_publish_news', 'Can publish news articles')], 'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark as featured to show prominently.', verbose_name='Featured'),
        ),
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this article has been viewed.', verbose_name='View Count'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(db_index=True, help_text='Name of the article author.', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full article content with rich text formatting.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional featured image (recommended: 1200x630px).', null=True, upload_to='news/images/%Y/%m/', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Check to make this article visible to users.', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Internal flag to track read status.', verbose_name='Mark as Read'),
        ),
        migrations.AlterField(
            model_name='news',
            name='module',
            field=models.CharField(choices=[('member', 'Member'), ('facilitator', 'Facilitator'), ('sahayak', 'Sahayak'), ('admin', 'Admin'), ('all', 'All Modules')], db_index=True, default='member', help_text='Which module this news is for.', max_length=50, verbose_name='Target Module'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when article was first published.', verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(help_text='Unique identifier for the news article (auto-generated from title).', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(help_text='Brief summary (max 500 characters) - shown in listings.', max_length=500, validators=[django.core.validators.MinLengthValidator(10, 'Summary must be at least 10 characters.')], verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for categorization (e.g., policy, update, event).', max_length=255, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, help_text='Enter the title of the news article (max 255 characters).', max_length=255, validators=[django.core.validators.MinLengthValidator(5, 'Title must be at least 5 characters long.')], verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of last update.', verbose_name='Updated Date'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_date', 'is_published'], name='news_pub_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['module', 'is_published', '-published_date'], name='news_module_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_published', 'is_featured', '-published_date'], name='news_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['author', '-published_date'], name='news_author_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.CheckConstraint(check=models.Q(('view_count__gte', 0)), name='member_news_positive_view_count', violation_error_message='View count cannot be negative.'),
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
        migrations.DeleteModel(
            name='FeedbackLog',
        ),
        migrations.DeleteModel(
            name='SahayakFeedback',
        ),
    ]
