# Generated by Django 4.2 on 2025-12-05 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('member', '0021_remove_feedbacklog_feedback_remove_feedbacklog_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text='Unique identifier for programmatic access', max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, choices=[('LayoutDashboard', 'Dashboard'), ('Package', 'Package'), ('Users', 'Users'), ('User', 'User'), ('UserCheck', 'User Check'), ('Shield', 'Shield'), ('BarChart3', 'Bar Chart'), ('TrendingUp', 'Trending Up'), ('BarChart', 'Bar Chart Simple'), ('DollarSign', 'Dollar Sign'), ('Settings', 'Settings'), ('Sliders', 'Sliders'), ('Plug', 'Plug'), ('HelpCircle', 'Help Circle')], max_length=50)),
                ('path', models.CharField(blank=True, help_text='Internal route path or external URL', max_length=500, null=True)),
                ('is_external', models.BooleanField(default=False, help_text='Whether the path is an external URL')),
                ('opens_new_tab', models.BooleanField(default=False)),
                ('badge_resolver', models.CharField(blank=True, help_text="Python path to badge resolver function (e.g., 'menu.badges.get_pending_count')", max_length=255)),
                ('badge_color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('gray', 'Gray')], default='red', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Hide from menu but keep accessible via direct URL')),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('css_class', models.CharField(blank=True, max_length=100)),
                ('feature_flag', models.CharField(blank=True, help_text='Feature flag to check before showing this menu item', max_length=100)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='member.menuitem')),
                ('required_permissions', models.ManyToManyField(blank=True, help_text='User must have ALL these permissions', related_name='menu_items', to='auth.permission')),
            ],
            options={
                'db_table': 'menu_items',
                'ordering': ['tree_id', 'lft', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserMenuPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_collapsed', models.BooleanField(default=False)),
                ('custom_order', models.IntegerField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.menuitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_user_preferences',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('schema_name', models.CharField(blank=True, max_length=63, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority roles take precedence')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='auth.group')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='member.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_roles',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Leave empty for public access', related_name='menu_items', to='member.role'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='member.tenant'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MenuAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usermenupreference',
            index=models.Index(fields=['user', 'is_pinned'], name='menu_user_p_user_id_88b89a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermenupreference',
            unique_together={('user', 'menu_item')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code', 'is_active'], name='menu_roles_code_eb1013_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'is_active'], name='menu_roles_tenant__660211_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['parent', 'is_active', 'is_visible'], name='menu_items_parent__0fe3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['tenant', 'is_active'], name='menu_items_tenant__1429fb_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['code', 'tenant'], name='menu_items_code_160759_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['tree_id', 'lft'], name='member_menuitem_tree_id_lf45e3'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('code', 'tenant'), name='unique_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='menuaccesslog',
            index=models.Index(fields=['user', '-accessed_at'], name='menu_access_user_id_aaaa31_idx'),
        ),
        migrations.AddIndex(
            model_name='menuaccesslog',
            index=models.Index(fields=['menu_item', '-accessed_at'], name='menu_access_menu_it_b82d71_idx'),
        ),
    ]
