# Generated by Django 4.2 on 2025-01-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedMppToFacilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpp_code', models.CharField(max_length=9, unique=True)),
                ('mpp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mpp_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mpp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('mpp_logo', models.CharField(blank=True, max_length=150, null=True)),
                ('mpp_icon', models.CharField(blank=True, max_length=150, null=True)),
                ('mpp_punch_line', models.CharField(blank=True, max_length=100, null=True)),
                ('mpp_opening_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assigned MPP to Facilitator',
                'verbose_name_plural': 'Assigned MPPs to Facilitators',
                'db_table': 'assigned_mpp_to_facilitator',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='assignedmpptofacilitator',
            constraint=models.UniqueConstraint(fields=('mpp_code',), name='unique_mpp_code'),
        ),
    ]
