# Generated by Django 4.2 on 2025-01-16 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilitator', '0003_alter_assignedmpptofacilitator_sahayak_apikey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedmpptofacilitator',
            name='mpp_ex_code',
            field=models.CharField(blank=True, help_text='An external code for the MPP, if applicable.', max_length=20, null=True, verbose_name='MPP External Code'),
        ),
        migrations.AlterField(
            model_name='assignedmpptofacilitator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the MPP assignment was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='assignedmpptofacilitator',
            name='mpp_code',
            field=models.CharField(help_text='A unique code assigned to the MPP. This code must be 9 characters long.', max_length=9, unique=True, verbose_name='MPP Code'),
        ),
        migrations.AlterField(
            model_name='assignedmpptofacilitator',
            name='mpp_icon',
            field=models.CharField(blank=True, help_text='The URL or path to the icon image of the MPP.', max_length=150, null=True, verbose_name='MPP Icon URL'),
        ),
        migrations.AlterField(
            model_name='assignedmpptofacilitator',
            name='mpp_logo',
            field=models.CharField(blank=True, help_text='The URL or path to the logo image of the MPP.', max_length=150, null=True, verbose_name='MPP Logo URL'),
        ),
        migrations.AlterField(
            model_name='assignedmpptofacilitator',
            name='mpp_name',
            field=models.CharField(blank=True, help_text='The full name of the MPP.', max_length=255, null=True, verbose_name='MPP Name'),
        ),
        migrations.AlterField(
            model_name='assignedmpptofacilitator',
            name='mpp_opening_date',
            field=models.DateTimeField(blank=True, help_text='The date and time when the MPP is officially opened.', null=True, verbose_name='MPP Opening Date'),
        ),
        migrations.AlterField(
            model_name='assignedmpptofacilitator',
            name='mpp_punch_line',
            field=models.CharField(blank=True, help_text='A catchy tagline or punch line associated with the MPP.', max_length=100, null=True, verbose_name='MPP Punch Line'),
        ),
        migrations.AlterField(
            model_name='assignedmpptofacilitator',
            name='mpp_short_name',
            field=models.CharField(blank=True, help_text='A short name or abbreviation for the MPP.', max_length=50, null=True, verbose_name='MPP Short Name'),
        ),
        migrations.AlterField(
            model_name='assignedmpptofacilitator',
            name='mpp_type',
            field=models.CharField(blank=True, help_text='The type/category of the MPP.', max_length=20, null=True, verbose_name='MPP Type'),
        ),
        migrations.AlterField(
            model_name='assignedmpptofacilitator',
            name='sahayak',
            field=models.ForeignKey(blank=True, help_text='The user assigned as the facilitator for this MPP.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpps', to=settings.AUTH_USER_MODEL, verbose_name='Facilitator'),
        ),
        migrations.AlterField(
            model_name='assignedmpptofacilitator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the MPP assignment was last updated.', verbose_name='Updated At'),
        ),
    ]
