# Generated by Django 4.2 on 2025-04-28 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0005_membercomplaintreason_membercomplaintreport_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vcgmeeting',
            name='unique_mpp_name_code',
        ),
        migrations.RemoveField(
            model_name='monthassignment',
            name='no_of_pourers',
        ),
        migrations.AddField(
            model_name='vcgroup',
            name='mpp',
            field=models.ForeignKey(blank=True, help_text='Member related to  mpp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilitator.assignedmpptofacilitator', verbose_name='MPP'),
        ),
        migrations.AlterField(
            model_name='vcgroup',
            name='member_ex_code',
            field=models.CharField(blank=True, help_text='Unique identifier for the VCG member.', max_length=20, null=True, unique=True, verbose_name='Member Ex Code'),
        ),
        migrations.AddConstraint(
            model_name='vcgmeeting',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'started')), fields=('mpp_name', 'mpp_code', 'started_at'), name='unique_mpp_meeting_per_month'),
        ),
    ]
