# Generated by Django 4.2 on 2025-04-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0006_remove_vcgmeeting_unique_mpp_name_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcgmeeting',
            name='mpp_code',
            field=models.CharField(blank=True, help_text='Unique MPP code assigned.', max_length=100, null=True, verbose_name='MPP Code'),
        ),
        migrations.AlterField(
            model_name='vcgmeeting',
            name='mpp_ex_code',
            field=models.CharField(blank=True, default='', help_text='External MPP Code for reference.', max_length=100, null=True, verbose_name='MPP EX Code'),
        ),
        migrations.AlterField(
            model_name='vcgmeeting',
            name='mpp_name',
            field=models.CharField(blank=True, default='', help_text='Name of the MPP associated with the meeting.', max_length=100, null=True, verbose_name='MPP Name'),
        ),
    ]
