# Generated by Django 4.2 on 2025-06-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0007_alter_vcgmeeting_mpp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcgroup',
            name='mpp_code',
            field=models.CharField(blank=True, help_text='Unique mpp code.', max_length=20, null=True, verbose_name='Mpp Code'),
        ),
    ]
