# Generated by Django 4.2 on 2025-06-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0008_vcgroup_mpp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcgmeeting',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicated whether data is deleted or not.', verbose_name='deleted'),
        ),
    ]
