# Generated by Django 4.2 on 2025-06-20 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilitator', '0010_alter_vcgmeeting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('support', 'Support'), ('it', 'IT'), ('pib', 'PIB'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('engineering', 'Engineering'), ('admin', 'Administration')], help_text='Department or team of the user.', max_length=32, null=True, verbose_name='Department')),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture.', null=True, upload_to='profile_images/', verbose_name='Avatar')),
                ('phone_number', models.CharField(blank=True, help_text='Contact number of the user.', max_length=15, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, help_text='Residential or official address.', null=True, verbose_name='Address')),
                ('designation', models.CharField(blank=True, help_text='Official designation or title.', max_length=100, null=True, verbose_name='Designation')),
                ('is_verified', models.BooleanField(default=False, help_text="Indicates whether the user's profile is verified.", verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(help_text='The user to whom this profile belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['department', 'user__username'],
            },
        ),
    ]
