# Generated by Django 4.2 on 2025-06-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text="Indicates whether the user's email is verified.", verbose_name='Email Verified'),
        ),
    ]
