# Generated by Django 4.2 on 2025-07-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0014_updaterequest_updateauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterequest',
            name='mcc_code',
            field=models.CharField(blank=True, help_text='A short name or abbreviation for the MPP.', max_length=50, null=True, verbose_name='MPP Short Name'),
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='mpp_code',
            field=models.CharField(blank=True, help_text='A unique code assigned to the MPP. This code must be 9 characters long.', max_length=9, null=True, verbose_name='MPP Code'),
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='mpp_ex_code',
            field=models.CharField(blank=True, help_text='An external code for the MPP, if applicable.', max_length=20, null=True, verbose_name='MPP External Code'),
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='mpp_name',
            field=models.CharField(blank=True, help_text='The full name of the MPP.', max_length=255, null=True, verbose_name='MPP Name'),
        ),
    ]
