# Generated by Django 4.2 on 2025-07-18 07:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilitator', '0015_updaterequest_mcc_code_updaterequest_mpp_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateRequestData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates whether this entry has been deleted.', verbose_name='Deleted')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='New Value')),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('file', 'File'), ('json', 'JSON')], default='text', max_length=20, verbose_name='Data Type')),
            ],
            options={
                'verbose_name': 'Update Request Data',
                'verbose_name_plural': 'Update Request Data',
            },
        ),
        migrations.CreateModel(
            name='UpdateRequestDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates whether this entry has been deleted.', verbose_name='Deleted')),
                ('document_type', models.CharField(choices=[('passbook', 'Passbook Copy'), ('application', 'Application Letter'), ('affidavit', 'Affidavit Copy'), ('id_proof', 'ID Proof'), ('other', 'Oher')], max_length=50, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='update_requests/%Y/%m/%d/', verbose_name='Document File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file_size', models.PositiveIntegerField(verbose_name='File Size (bytes)')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Update Request Document',
                'verbose_name_plural': 'Update Request Documents',
            },
        ),
        migrations.CreateModel(
            name='UpdateRequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates whether this entry has been deleted.', verbose_name='Deleted')),
                ('change_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('STATUS_CHANGE', 'Status Changed'), ('REVIEW', 'Reviewed')], max_length=20, verbose_name='Change Type')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='New Value')),
                ('change_reason', models.TextField(blank=True, null=True, verbose_name='Change Reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Additional Metadata')),
            ],
            options={
                'verbose_name': 'Update Request History',
                'verbose_name_plural': 'Update Request Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='updateauditlog',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='updateauditlog',
            name='update_request',
        ),
        migrations.AlterModelOptions(
            name='updaterequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Update Request', 'verbose_name_plural': 'Update Requests'},
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='affidavit_file',
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='member_application',
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='new_mobile_number',
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='passbook_image',
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='requested_at',
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates whether this entry has been deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='request_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated unique request identifier (e.g., REQ-2025-001234)', max_length=20, null=True, unique=True, verbose_name='Request ID'),
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='member_code',
            field=models.CharField(blank=True, help_text='Unique identifier for the member.', max_length=20, null=True, verbose_name='Member Code'),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='member_ex_code',
            field=models.CharField(blank=True, help_text='Unique identifier for the member.', max_length=20, null=True, verbose_name='Member Ex Code'),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='member_name',
            field=models.CharField(blank=True, help_text='Full name of the member.', max_length=100, null=True, verbose_name='Member Name'),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='mobile_number',
            field=models.CharField(blank=True, help_text="Member's current WhatsApp contact number.", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid WhatsApp number with country code (e.g., +1234567890).', regex='^\\+?\\d{10,15}$')], verbose_name='Current WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='updaterequest',
            index=models.Index(fields=['member_code', 'status'], name='facilitator_member__607ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='updaterequest',
            index=models.Index(fields=['created_by', 'created_at'], name='facilitator_created_f032e4_idx'),
        ),
        migrations.AddIndex(
            model_name='updaterequest',
            index=models.Index(fields=['status', 'request_type'], name='facilitator_status_85d6b9_idx'),
        ),
        migrations.DeleteModel(
            name='UpdateAuditLog',
        ),
        migrations.AddField(
            model_name='updaterequesthistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AddField(
            model_name='updaterequesthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='updaterequesthistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='facilitator.updaterequest'),
        ),
        migrations.AddField(
            model_name='updaterequesthistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='updaterequestdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='updaterequestdocument',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='facilitator.updaterequest'),
        ),
        migrations.AddField(
            model_name='updaterequestdocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='updaterequestdata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='updaterequestdata',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_data', to='facilitator.updaterequest'),
        ),
        migrations.AddField(
            model_name='updaterequestdata',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='updaterequesthistory',
            index=models.Index(fields=['request', 'created_at'], name='facilitator_request_e177c0_idx'),
        ),
        migrations.AddIndex(
            model_name='updaterequesthistory',
            index=models.Index(fields=['changed_by', 'created_at'], name='facilitator_changed_603be1_idx'),
        ),
        migrations.AddIndex(
            model_name='updaterequesthistory',
            index=models.Index(fields=['change_type', 'created_at'], name='facilitator_change__c1e4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='updaterequestdocument',
            index=models.Index(fields=['request', 'document_type'], name='facilitator_request_2fa06c_idx'),
        ),
        migrations.AddIndex(
            model_name='updaterequestdata',
            index=models.Index(fields=['request', 'field_name'], name='facilitator_request_139ce8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='updaterequestdata',
            unique_together={('request', 'field_name')},
        ),
    ]
