# Generated by Django 4.2 on 2025-07-24 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0016_updaterequestdata_updaterequestdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterequest',
            name='mobile_number',
            field=models.CharField(blank=True, help_text="Member's  contact number.", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid WhatsApp number with country code (e.g., +1234567890).', regex='^\\+?\\d{10,15}$')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='updaterequestdocument',
            name='document_type',
            field=models.CharField(choices=[('passbook', 'Passbook Copy'), ('application', 'Application Letter'), ('affidavit', 'Affidavit Copy')], max_length=50, verbose_name='Document Type'),
        ),
    ]
