# Generated by Django 4.2 on 2025-07-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0017_alter_updaterequest_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('UPDATED', 'Updated')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
    ]
