# Generated by Django 4.2 on 2025-07-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0018_alter_updaterequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('support', 'Support'), ('it', 'IT'), ('pib', 'PIB'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('engineering', 'Engineering'), ('admin', 'Administration'), ('veterinarian', 'Veterinarian'), ('mait', 'MAIT'), ('doctor', 'Doctor')], help_text='Department or team of the user.', max_length=32, null=True, verbose_name='Department'),
        ),
    ]
