# Generated by Django 4.2 on 2025-07-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0019_alter_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salutation',
            field=models.CharField(blank=True, help_text='Prefix such as Dr., Mr., Ms., etc.', max_length=10, null=True, verbose_name='Salutation'),
        ),
    ]
