# Generated by Django 4.2 on 2025-07-31 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0020_userprofile_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text='The supervisor or manager to whom this user reports.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to='facilitator.userprofile', verbose_name='Reports To'),
        ),
    ]
