# Generated by Django 4.2 on 2025-08-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0021_userprofile_reports_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['department', 'user__username'], 'permissions': [('can_view_others_reportees', 'Can view reportees of other users')], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
