# Generated by Django 4.2 on 2025-08-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0022_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mpp_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MPP Code'),
        ),
    ]
