# Generated by Django 4.2 on 2025-10-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0023_userprofile_mpp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('support', 'Support'), ('it', 'IT'), ('pib', 'PIB'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('engineering', 'Engineering'), ('admin', 'Administration'), ('veterinarian', 'Veterinarian'), ('mait', 'MAIT'), ('doctor', 'Doctor'), ('sahayak', 'Sahayak'), ('member', 'Member')], help_text='Department or team of the user.', max_length=32, null=True, verbose_name='Department'),
        ),
    ]
