# Generated by Django 4.2 on 2025-11-10 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilitator', '0024_alter_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('support', 'Support'), ('it', 'IT'), ('pib', 'PIB'), ('sales', 'Sales'), ('engineering', 'Engineering'), ('admin', 'Administration'), ('veterinarian', 'Veterinarian'), ('mait', 'MAIT'), ('doctor', 'Doctor'), ('sahayak', 'Sahayak'), ('member', 'Member')], help_text='Department or team of the user.', max_length=32, null=True, verbose_name='Department'),
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc_code', models.CharField(blank=True, help_text='Unique identifier for the MCC (from external DB).', max_length=20, null=True, verbose_name='MCC Code')),
                ('mcc_ex_code', models.CharField(blank=True, help_text='External reference code for the MCC, if available.', max_length=50, null=True, verbose_name='MCC External Code')),
                ('mcc_name', models.CharField(blank=True, help_text='Display name of the MCC location.', max_length=255, null=True, verbose_name='MCC Name')),
                ('mpp_code', models.CharField(blank=True, help_text='Unique identifier for the MPP (from external DB).', max_length=20, null=True, verbose_name='MPP Code')),
                ('mpp_ex_code', models.CharField(blank=True, help_text='External reference code for the MPP, if available.', max_length=50, null=True, verbose_name='MPP External Code')),
                ('mpp_name', models.CharField(blank=True, help_text='Display name of the MPP location.', max_length=255, null=True, verbose_name='MPP Name')),
                ('is_primary', models.BooleanField(default=False, help_text="Marks this location as the user's main or default work location.", verbose_name='Primary Location')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this user was assigned to the location.', verbose_name='Assigned At')),
                ('active', models.BooleanField(default=True, help_text='Indicates if this user-location assignment is currently active.', verbose_name='Active Assignment')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or comments about this assignment.', null=True, verbose_name='Remarks')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Administrator or supervisor who assigned this location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_locations', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('user', models.ForeignKey(help_text='The user assigned to this operational location.', on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Location',
                'verbose_name_plural': 'User Locations',
                'ordering': ['user__username', 'mcc_code', 'mpp_code'],
            },
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user'], name='idx_userlocation_user'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['mcc_code'], name='idx_userlocation_mcc_code'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['mpp_code'], name='idx_userlocation_mpp_code'),
        ),
        migrations.AddConstraint(
            model_name='userlocation',
            constraint=models.UniqueConstraint(fields=('user', 'mcc_code', 'mpp_code'), name='unique_user_mcc_mpp_assignment', violation_error_message='This user is already assigned to the specified MCC-MPP combination.'),
        ),
    ]
