# Generated by Django 4.2 on 2025-11-19 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilitator', '0025_alter_userprofile_department_userlocation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlocation',
            options={'ordering': ['-assigned_at'], 'permissions': [('assign_location', 'Can assign locations to users'), ('bulk_assign_location', 'Can bulk assign locations'), ('view_all_locations', 'Can view all user locations')], 'verbose_name': 'User Location', 'verbose_name_plural': 'User Locations'},
        ),
        migrations.RemoveConstraint(
            model_name='userlocation',
            name='unique_user_mcc_mpp_assignment',
        ),
        migrations.RemoveIndex(
            model_name='userlocation',
            name='idx_userlocation_user',
        ),
        migrations.RemoveIndex(
            model_name='userlocation',
            name='idx_userlocation_mcc_code',
        ),
        migrations.RemoveIndex(
            model_name='userlocation',
            name='idx_userlocation_mpp_code',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='mcc_ex_code',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='level',
            field=models.CharField(choices=[('mcc', 'MCC Level'), ('route', 'Route Level'), ('mpp', 'MPP Level')], db_index=True, default='route', help_text='Hierarchy level at which the user is assigned (MCC, Route, or MPP)', max_length=10),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='mcc_tr_code',
            field=models.CharField(blank=True, help_text='Transaction/Reference code for MCC (legacy system identifier)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last modification'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='route_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique code identifying the distribution route', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='route_ex_code',
            field=models.CharField(blank=True, help_text='External/legacy system code for the route', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='route_name',
            field=models.CharField(blank=True, help_text='Display name of the distribution route', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this location assignment is currently active'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this location was assigned'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who created this location assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, help_text="Indicates if this is the user's primary/default location"),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='mcc_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique code identifying the Market Collection Center', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='mcc_name',
            field=models.CharField(blank=True, help_text='Display name of the Market Collection Center', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='mpp_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique code identifying the Milk Procurement Point', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='mpp_ex_code',
            field=models.CharField(blank=True, help_text='External/legacy system code for the MPP', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='mpp_name',
            field=models.CharField(blank=True, help_text='Display name of the Milk Procurement Point', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or comments about this assignment', null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(help_text='User to whom this location is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user', 'level', 'active'], name='idx_user_level_active'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user', 'is_primary', 'active'], name='idx_user_primary'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['level', 'active'], name='idx_level_active'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['mcc_code', 'active'], name='idx_mcc_active'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['route_code', 'active'], name='idx_route_active'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['mpp_code', 'active'], name='idx_mpp_active'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['assigned_by', 'assigned_at'], name='idx_assigned_by_at'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['assigned_at', 'active'], name='idx_time_active'),
        ),
        migrations.AddConstraint(
            model_name='userlocation',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user', 'level', 'mcc_code', 'route_code', 'mpp_code'), name='unique_active_location_per_user'),
        ),
        migrations.AlterModelTable(
            name='userlocation',
            table='tbl_user_locations',
        ),
    ]
