# Generated by Django 4.2 on 2025-07-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
    ]
