# Generated by Django 4.2 on 2025-07-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0003_cattlestatuslog_cattlestatustype_membersmastercopy_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cattlestatuslog',
            name='veterinary__status__3f365e_idx',
        ),
        migrations.RemoveField(
            model_name='cattlestatuslog',
            name='status',
        ),
        migrations.AddField(
            model_name='cattle',
            name='age_year',
            field=models.PositiveIntegerField(blank=True, help_text='Age of the cattle in year.', null=True, verbose_name='Age (year)'),
        ),
        migrations.AddField(
            model_name='cattle',
            name='no_of_calving',
            field=models.PositiveIntegerField(blank=True, help_text='No Of Calving.', null=True, verbose_name='Age (year)'),
        ),
        migrations.AddField(
            model_name='cattlestatuslog',
            name='last_calving_month',
            field=models.CharField(blank=True, choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], help_text='Month of last calving (optional)', max_length=10, null=True, verbose_name='Last Calving Month'),
        ),
        migrations.AddField(
            model_name='cattlestatuslog',
            name='pregnancy_status',
            field=models.BooleanField(default=False, help_text='Indicates whether the cattle is pregnant.', verbose_name='Pregnancy Status'),
        ),
        migrations.AddField(
            model_name='cattlestatuslog',
            name='statuses',
            field=models.ManyToManyField(help_text='Multiple statuses like MILKING, PREGNANT, DRY etc.', related_name='cattle_logs', to='veterinary.cattlestatustype', verbose_name='Cattle Statuses'),
        ),
    ]
