# Generated by Django 4.2 on 2025-07-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0005_animaldiagnosis_animaltreatment_caseentry_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentmethod',
            name='valid_locale_check',
        ),
        migrations.AddField(
            model_name='diagnosisroute',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='animaldiagnosis',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='animaltreatment',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='caseentry',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='casereceiverlog',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='cattlecasestatus',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='cattlecasetype',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='cattlestatuslog',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='cattlestatustype',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='cattletagging',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='diagnosedsymptomhistory',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='location',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='species',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='speciesbreed',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='usermedicinestock',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.CheckConstraint(check=models.Q(('locale__in', ['en', 'hi', 'ur'])), name='valid_locale_check'),
        ),
    ]
