# Generated by Django 4.2 on 2025-08-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0008_observationtype_farmerobservation_farmermeeting_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='farmermeeting',
            name='idx_farmermeeting_member',
        ),
        migrations.RemoveField(
            model_name='farmermeeting',
            name='member',
        ),
        migrations.AddField(
            model_name='farmermeeting',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Members who attended or are associated with this meeting.', related_name='farmer_meetings', to='veterinary.membersmastercopy', verbose_name='Members'),
        ),
    ]
