# Generated by Django 4.2 on 2025-08-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0009_remove_farmermeeting_idx_farmermeeting_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmermeeting',
            name='notes',
            field=models.TextField(blank=True, help_text='Any notes(optional)', null=True, verbose_name='Additional Notes'),
        ),
    ]
