# Generated by Django 4.2 on 2025-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0010_farmermeeting_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerobservation',
            name='notes',
            field=models.TextField(blank=True, help_text='Any remarks from field vet or technician', null=True),
        ),
    ]
