# Generated by Django 4.2 on 2025-08-27 07:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinary', '0011_farmerobservation_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermedicinetransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Medicine Transaction', 'verbose_name_plural': 'User Medicine Transactions'},
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location where this stock is held', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_stocks', to='veterinary.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity reserved/allocated to users', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='medicinestockaudit',
            name='balance_after',
            field=models.FloatField(default=0.0, help_text='Stock balance after this transaction', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balance After Transaction'),
        ),
        migrations.AddField(
            model_name='usermedicinestock',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', help_text='Sync status for offline/online data sync', max_length=20),
        ),
        migrations.AddField(
            model_name='usermedicinetransaction',
            name='performed_by',
            field=models.ForeignKey(help_text='User who performed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_medicine_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermedicinetransaction',
            name='running_balance',
            field=models.FloatField(default=0.0, help_text='Remaining stock balance for this user after this transaction', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Running Balance'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine',
            field=models.CharField(db_index=True, help_text='Name of the medicine', max_length=100, verbose_name='Medicine'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='medicine_form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('liquid', 'Liquid'), ('injection', 'Injection'), ('capsule', 'Capsule'), ('ointment', 'Ointment'), ('powder', 'Powder'), ('paste', 'Paste'), ('tube', 'Tube'), ('bolus', 'Bolus'), ('suspension', 'Suspension'), ('solution', 'Solution'), ('spray', 'Spray'), ('drops', 'Eye/Ear/Nose Drops'), ('cream', 'Cream'), ('lotion', 'Lotion'), ('shampoo', 'Medicated Shampoo'), ('feed_additive', 'Feed Additive'), ('implant', 'Implant'), ('inhalant', 'Inhalant'), ('transdermal_patch', 'Transdermal Patch'), ('suppository', 'Suppository'), ('drench', 'Drench'), ('pour_on', 'Pour-On'), ('intramammary', 'Intramammary'), ('other', 'Other')], default='tablet', help_text='Form in which the medicine is administered', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total stock for this batch', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='medicinestockaudit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinestockaudit',
            name='quantity',
            field=models.FloatField(help_text='Quantity added/removed'),
        ),
        migrations.AlterField(
            model_name='medicinestockaudit',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment')], max_length=10),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='veterinary.location'),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='medicine_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.medicinestock'),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='quantity_transferred',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_transfers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='veterinary.location'),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='transfer_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='transfer_type',
            field=models.CharField(choices=[('inward', 'Inward'), ('outward', 'Outward'), ('return', 'Return')], default='outward', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='transferred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_transfers_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicinestocktransferlog',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='usermedicinestock',
            name='allocated_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity allocated from the stock (e.g., 10 tablets or 50 ml)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usermedicinestock',
            name='min_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Critical threshold value for reminder when stock is very low', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usermedicinestock',
            name='sync',
            field=models.BooleanField(default=False, help_text='Indicates if the record is synced with the server', verbose_name='Synced'),
        ),
        migrations.AlterField(
            model_name='usermedicinestock',
            name='threshold_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Warning threshold to trigger refill reminder', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usermedicinestock',
            name='used_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity already used by the user', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usermedicinetransaction',
            name='action',
            field=models.CharField(choices=[('ALLOCATED', 'Allocated'), ('USED', 'Used'), ('RETURNED', 'Returned')], default='ALLOCATED', help_text='Allocated, Used, or Returned', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermedicinetransaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermedicinetransaction',
            name='quantity',
            field=models.FloatField(help_text='Quantity involved in this transaction (e.g., 10 tablets, 5 ml)'),
        ),
        migrations.AlterField(
            model_name='usermedicinetransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When this transaction occurred'),
        ),
        migrations.AlterUniqueTogether(
            name='medicinestock',
            unique_together={('medicine', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='medicinestock',
            index=models.Index(fields=['batch_number'], name='tbl_medicin_batch_n_fcfe22_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinestock',
            index=models.Index(fields=['expiry_date'], name='tbl_medicin_expiry__1cb883_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermedicinestock',
            constraint=models.CheckConstraint(check=models.Q(('used_quantity__lte', models.F('allocated_quantity'))), name='used_lte_allocated'),
        ),
    ]
