# Generated by Django 4.2 on 2025-08-28 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinary', '0012_alter_usermedicinetransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedicinestock',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='Date when the allocation was approved/rejected', null=True),
        ),
        migrations.AddField(
            model_name='usermedicinestock',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Approval status by reporting head', max_length=20),
        ),
        migrations.AddField(
            model_name='usermedicinestock',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Reporting head who approved/rejected the allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermedicinestock',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='medicinestock',
            unique_together={('medicine', 'batch_number', 'location')},
        ),
        migrations.AddIndex(
            model_name='medicinestock',
            index=models.Index(fields=['location'], name='tbl_medicin_locatio_789338_idx'),
        ),
    ]
