# Generated by Django 4.2 on 2025-09-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0013_usermedicinestock_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedicinestock',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Approval status by reporting head', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='usermedicinestock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'medicine_stock'), name='unique_active_user_medicine_allocation'),
        ),
    ]
