# Generated by Django 4.2 on 2025-09-09 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinary', '0014_alter_usermedicinestock_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Original filename of the uploaded Excel file', max_length=255)),
                ('file', models.FileField(blank=True, help_text='Path to the uploaded file in storage', null=True, upload_to='uploads/excel/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when processing finished', null=True)),
                ('processed', models.BooleanField(default=False)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, help_text='Any error details if processing failed', null=True)),
                ('sheets_data', models.JSONField(blank=True, default=dict, help_text='Stores preview/sample data or metadata from sheets')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra info about the upload (columns, mapping, etc.)')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who initiated the upload', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excel Upload Session',
                'verbose_name_plural': 'Excel Upload Sessions',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exceluploadsession',
            index=models.Index(fields=['status'], name='veterinary__status_69c566_idx'),
        ),
        migrations.AddIndex(
            model_name='exceluploadsession',
            index=models.Index(fields=['uploaded_at'], name='veterinary__uploade_f5c61d_idx'),
        ),
    ]
