# Generated by Django 4.2 on 2025-09-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0015_exceluploadsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattlestatuslog',
            name='milk_production_lpd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average milk production in Liters per Day.', max_digits=6, null=True, verbose_name='Milk Production (LPD)'),
        ),
        migrations.AddField(
            model_name='cattletagging',
            name='virtual_tag_no',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated virtual tag number', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='cattletagging',
            index=models.Index(fields=['virtual_tag_no'], name='tbl_cattle__virtual_abeb5b_idx'),
        ),
    ]
