# Generated by Django 4.2 on 2025-09-15 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinary', '0016_cattlestatuslog_milk_production_lpd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CattleOwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the record is active', verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates whether the record is soft-deleted', verbose_name='Is Deleted')),
                ('sync', models.BooleanField(default=False, help_text='Indicates if the record is synced with the server', verbose_name='Synced')),
                ('locale', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale')),
                ('transfer_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('transfer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'tbl_cattle_ownership_history',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='cattlestatuslog',
            options={'ordering': ['-from_date', '-created_at'], 'verbose_name': 'Cattle Status Log', 'verbose_name_plural': 'Cattle Status Logs'},
        ),
        migrations.RemoveIndex(
            model_name='cattletagging',
            name='tbl_cattle__tag_num_fb33a1_idx',
        ),
        migrations.AddField(
            model_name='cattle',
            name='cattle_code',
            field=models.CharField(blank=True, editable=False, help_text='Deterministic unique cattle identifier', max_length=40, null=True, unique=True, verbose_name='Cattle Code'),
        ),
        migrations.AddField(
            model_name='cattle',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='is_sold',
            field=models.BooleanField(default=False, help_text='Whether this cattle has been sold'),
        ),
        migrations.AddField(
            model_name='cattle',
            name='last_status_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cattlestatuslog',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Whether this is the current active status'),
        ),
        migrations.AddField(
            model_name='cattlestatuslog',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded this status', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cattletagging',
            name='tag_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged'), ('REPLACED', 'Replaced')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='no_of_calving',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='No Of Calving.', null=True, verbose_name='Lactation Count'),
        ),
        migrations.AlterField(
            model_name='cattlestatuslog',
            name='milk_production_lpd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Average milk production in Liters per Day.', max_digits=6, null=True, verbose_name='Milk Production (LPD)'),
        ),
        migrations.AlterField(
            model_name='cattletagging',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tagging/images/'),
        ),
        migrations.AlterField(
            model_name='cattletagging',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this tag is currently active'),
        ),
        migrations.AlterField(
            model_name='cattletagging',
            name='tag_number',
            field=models.CharField(help_text='Physical tag number for the cattle (e.g., IND-12345)', max_length=20, verbose_name='Tag Number'),
        ),
        migrations.AddIndex(
            model_name='cattle',
            index=models.Index(fields=['cattle_code'], name='tbl_cattle_cattle__e6f806_idx'),
        ),
        migrations.AddIndex(
            model_name='cattle',
            index=models.Index(fields=['owner', 'is_alive'], name='tbl_cattle_owner_i_b100f6_idx'),
        ),
        migrations.AddIndex(
            model_name='cattle',
            index=models.Index(fields=['is_alive', 'is_sold'], name='tbl_cattle_is_aliv_ccbf60_idx'),
        ),
        migrations.AddIndex(
            model_name='cattlestatuslog',
            index=models.Index(fields=['cattle', 'is_current'], name='veterinary__cattle__da27dc_idx'),
        ),
        migrations.AddIndex(
            model_name='cattlestatuslog',
            index=models.Index(fields=['from_date', 'to_date'], name='veterinary__from_da_9620b7_idx'),
        ),
        migrations.AddIndex(
            model_name='cattletagging',
            index=models.Index(fields=['tag_number', 'is_active'], name='tbl_cattle__tag_num_c786aa_idx'),
        ),
        migrations.AddIndex(
            model_name='cattletagging',
            index=models.Index(fields=['tag_status'], name='tbl_cattle__tag_sta_9da65a_idx'),
        ),
        migrations.AddConstraint(
            model_name='cattle',
            constraint=models.CheckConstraint(check=models.Q(('is_sold', False), ('sold_date__isnull', False), _connector='OR'), name='sold_cattle_must_have_sold_date'),
        ),
        migrations.AddConstraint(
            model_name='cattle',
            constraint=models.CheckConstraint(check=models.Q(('is_alive', True), ('death_date__isnull', False), _connector='OR'), name='dead_cattle_must_have_death_date'),
        ),
        migrations.AddConstraint(
            model_name='cattlestatuslog',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('to_date__isnull', True)), fields=('cattle',), name='one_current_status_per_cattle'),
        ),
        migrations.AddConstraint(
            model_name='cattletagging',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tag_number',), name='unique_active_tag_number'),
        ),
        migrations.AddConstraint(
            model_name='cattletagging',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('cattle',), name='one_active_tag_per_cattle'),
        ),
        migrations.AddField(
            model_name='cattleownershiphistory',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='veterinary.cattle'),
        ),
        migrations.AddField(
            model_name='cattleownershiphistory',
            name='from_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattle_transferred_from', to='veterinary.membersmastercopy'),
        ),
        migrations.AddField(
            model_name='cattleownershiphistory',
            name='to_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattle_transferred_to', to='veterinary.membersmastercopy'),
        ),
        migrations.AddField(
            model_name='cattleownershiphistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
