# Generated by Django 4.2 on 2025-09-16 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0017_cattleownershiphistory_alter_cattlestatuslog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceluploadsession',
            name='task_id',
            field=models.CharField(default=uuid.uuid4, help_text='Task id of the uploaded Excel file', max_length=255),
        ),
        migrations.AlterField(
            model_name='exceluploadsession',
            name='file',
            field=models.FileField(blank=True, help_text='Path to the uploaded file in storage', null=True, upload_to='excel/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='exceluploadsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('queued', 'Queued')], db_index=True, default='pending', max_length=20),
        ),
    ]
