# Generated by Django 4.2 on 2025-09-20 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinary', '0019_costconfigurationhistory_nonmember_nonmembercattle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceluploadsession',
            name='filesize',
            field=models.CharField(blank=True, help_text='Original filesize of the uploaded Excel file', max_length=255, null=True, verbose_name='File size'),
        ),
        migrations.AlterField(
            model_name='exceluploadsession',
            name='error_message',
            field=models.TextField(blank=True, help_text='Any error details if processing failed', null=True, verbose_name='Error message'),
        ),
        migrations.AlterField(
            model_name='exceluploadsession',
            name='file',
            field=models.FileField(blank=True, help_text='Path to the uploaded file in storage', null=True, upload_to='excel/%Y/%m/%d/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='exceluploadsession',
            name='filename',
            field=models.CharField(help_text='Original filename of the uploaded Excel file', max_length=255, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='exceluploadsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra info about the upload (columns, mapping, etc.)', null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='exceluploadsession',
            name='sheets_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores preview/sample data or metadata from sheets', null=True, verbose_name='Sheets data'),
        ),
        migrations.AlterField(
            model_name='exceluploadsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('queued', 'Queued')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='exceluploadsession',
            name='task_id',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='Task id of the uploaded Excel file', max_length=255, verbose_name='Task ID'),
        ),
        migrations.AlterField(
            model_name='exceluploadsession',
            name='total_rows',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Total rows'),
        ),
        migrations.AlterField(
            model_name='exceluploadsession',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated the upload', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by'),
        ),
    ]
