# Generated by Django 4.2 on 2025-10-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0020_exceluploadsession_filesize_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='treatmentcostconfiguration',
            unique_together={('membership_type', 'time_slot', 'animal_tag_type', 'treatment_type', 'effective_from', 'locale')},
        ),
    ]
