# Generated by Django 4.2 on 2025-10-05 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0021_alter_treatmentcostconfiguration_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonmember',
            name='mobile_no',
            field=models.CharField(help_text='Mobile number', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
    ]
