# Generated by Django 4.2 on 2025-10-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0022_alter_nonmember_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='caseentry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current status of the case.', max_length=20, verbose_name='Case Status'),
        ),
        migrations.AlterField(
            model_name='cattlecasestatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', help_text='case status of cattle', max_length=20, verbose_name='Case Status'),
        ),
    ]
