# Generated by Django 4.2 on 2025-11-20 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinary', '0023_cattle_weight_kg_alter_caseentry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseentry',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Selected payment method for this case', null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinary.paymentmethod'),
        ),
        migrations.AddField(
            model_name='caseentry',
            name='requires_payment',
            field=models.BooleanField(default=True, help_text='Whether this case requires payment'),
        ),
        migrations.AlterField(
            model_name='casepayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Current status of the payment.', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('milk_bill', 'Milk Bill Payment')], max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CasePaymentSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the record is active', verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates whether the record is soft-deleted', verbose_name='Is Deleted')),
                ('sync', models.BooleanField(default=False, help_text='Indicates if the record is synced with the server', verbose_name='Synced')),
                ('locale', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='en-us', help_text='Locale used for this entry (e.g. en, hi, te)', max_length=10, verbose_name='Locale')),
                ('case_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment_summary', serialize=False, to='veterinary.caseentry')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total case cost', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid so far', max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, help_text='Remaining amount to be paid', max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue')], default='unpaid', help_text='Overall payment status for the case', max_length=20)),
                ('is_overdue', models.BooleanField(default=False, help_text='Whether any payment is overdue')),
                ('last_payment_date', models.DateTimeField(blank=True, help_text='Date of last payment', null=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Case Payment Summary',
                'verbose_name_plural': 'Case Payment Summaries',
            },
        ),
    ]
