# Generated by Django 4.2 on 2025-11-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0024_caseentry_payment_method_caseentry_requires_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepayment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for payment (applicable for milk bill)', null=True),
        ),
        migrations.AddField(
            model_name='casepayment',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, help_text='Last time payment retry was attempted', null=True),
        ),
        migrations.AddField(
            model_name='casepayment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about payment'),
        ),
        migrations.AddField(
            model_name='casepayment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Reference number for tracking', max_length=255),
        ),
        migrations.AddField(
            model_name='casepayment',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of payment retry attempts'),
        ),
    ]
