# Generated by Django 4.2 on 2025-11-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0025_casepayment_due_date_casepayment_last_retry_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', null=True, verbose_name='Created At'),
        ),
    ]
