# Generated by Django 4.2 on 2025-11-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0026_casepayment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
