# Generated by Django 4.2 on 2025-12-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0027_paymentmethod_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casepayment',
            name='payment_status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', help_text='Current status of the payment.', max_length=20, verbose_name='Payment Status'),
        ),
    ]
