# Generated by Django 4.2 on 2025-12-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0028_alter_casepayment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casepaymentsummary',
            name='case_entry',
        ),
        migrations.RemoveField(
            model_name='casepaymentsummary',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CasePayment',
        ),
        migrations.DeleteModel(
            name='CasePaymentSummary',
        ),
    ]
