# Generated by Django 4.2 on 2025-06-23 05:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or heading for the notification.', max_length=255, verbose_name='Title')),
                ('message', models.TextField(help_text='Detailed notification message to be shown.', validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Message')),
                ('model', models.CharField(help_text="Name of the model related to this notification, e.g., 'feedback', 'report'.", max_length=100, verbose_name='Model Type')),
                ('object_id', models.PositiveIntegerField(help_text='Primary key of the related model instance.', verbose_name='Object ID')),
                ('route', models.CharField(help_text='Frontend route name for redirection.', max_length=255, verbose_name='Route')),
                ('custom_key', models.CharField(blank=True, help_text='Optional key used for grouping or client-side logic.', max_length=100, null=True, verbose_name='Custom Key')),
                ('is_subroute', models.BooleanField(default=False, help_text='Indicates if the route is a sub-path or detail view.', verbose_name='Is Subroute')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('alert', 'Alert'), ('success', 'Success')], default='info', help_text='Classifies the type of notification.', max_length=20, verbose_name='Notification Type')),
                ('sent_via', models.CharField(choices=[('system', 'System'), ('fcm', 'Firebase Push'), ('email', 'Email')], default='system', help_text='Medium through which the notification was sent.', max_length=20, verbose_name='Sent Via')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the user has read the notification.', verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when the notification was read.', null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was created.', verbose_name='Created At')),
                ('deleted', models.BooleanField(default=False, help_text='Indicates whether this object has been deleted or not.', verbose_name='Deleted')),
                ('recipient', models.ForeignKey(help_text='User who will receive the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'App Notification',
                'verbose_name_plural': 'App Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_2b6ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='appnotification',
            index=models.Index(fields=['model', 'object_id'], name='notificatio_model_1ca858_idx'),
        ),
    ]
