# Generated by Django 4.2 on 2025-06-23 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='body',
            field=models.CharField(blank=True, help_text='Short summary or preview for the notification.', max_length=255, null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='User who triggered the notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
    ]
