# Generated by Django 4.2 on 2025-11-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationanalytics',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('webhook', 'Webhook')], default='push', max_length=200),
        ),
    ]
