# Generated by Django 4.2 on 2025-06-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_appnotification_body_appnotification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='delivery_attempted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last delivery attempt.', null=True, verbose_name='Delivery Attempted At'),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='delivery_response',
            field=models.JSONField(blank=True, help_text='Raw response from the notification delivery system (e.g., FCM).', null=True, verbose_name='Delivery Response'),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', help_text='Tracks whether the notification was successfully delivered.', max_length=20, verbose_name='Delivery Status'),
        ),
    ]
