# Generated by Django 4.2 on 2025-11-25 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_alter_notificationanalytics_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deep_link', models.CharField(db_index=True, max_length=512)),
                ('deep_path', models.CharField(blank=True, max_length=512)),
                ('module', models.CharField(choices=[('member', 'Member App'), ('sahayak', 'Sahayak App'), ('pes', 'PES App')], db_index=True, default='member', max_length=50)),
                ('android_package', models.CharField(max_length=200)),
                ('ios_bundle_id', models.CharField(blank=True, max_length=200)),
                ('fallback_url', models.URLField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('consumed', 'Consumed')], db_index=True, default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deep_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ['category', 'name', 'locale'], 'verbose_name': 'Notification Template', 'verbose_name_plural': 'Notification Templates'},
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='route_template',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='url_name',
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='action_buttons',
            field=models.JSONField(blank=True, default=list, help_text="List of action buttons for push notifications. Example: [{'label': 'View Order', 'action': 'open_order'}, {'label': 'Dismiss', 'action': 'dismiss'}]", verbose_name='Action Buttons'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='analytics_metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Additional metadata for analytics. Example: {'campaign': 'summer_sale', 'cohort': 'premium'}", verbose_name='Analytics Metadata'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='channel_config',
            field=models.JSONField(blank=True, default=dict, help_text="Optional per-channel settings. Example: {'email': {'from_name': 'Kashee Support', 'reply_to': 'support@kashee.com'}, 'push': {'sound': 'default', 'badge': 1}}", verbose_name='Channel-specific Configuration'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='deeplink_config',
            field=models.JSONField(blank=True, default=dict, help_text="Declarative deep link configuration. DeepLinkService will use this to generate links. Example: {  'module': 'member',   'url_name': 'order:detail',   'route_template': 'orders/{{ order.id }}/',   'fallback_template': 'https://kashee.com/orders/{{ order.id }}/',   'inapp_route': 'order/{{ order.id }}',   'deeplink_type': 'order_detail',   'expires_after': 7,   'max_uses': 1,   'metadata': {'source': 'notification'}}", verbose_name='Deep Link Configuration'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='description',
            field=models.TextField(blank=True, help_text="Internal description of this template's purpose and usage", verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='email_is_html',
            field=models.BooleanField(default=True, help_text='Whether email body should be rendered as HTML', verbose_name='Email is HTML'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='quiet_hours',
            field=models.JSONField(blank=True, default=dict, help_text="Do not send during these hours. Example: {'enabled': true, 'start': '22:00', 'end': '08:00', 'timezone': 'Asia/Kolkata'}", verbose_name='Quiet Hours'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='required_context_vars',
            field=models.JSONField(blank=True, default=list, help_text="List of required variables for this template. Example: ['order', 'user', 'amount']. Used for validation and documentation.", verbose_name='Required Context Variables'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='sample_context',
            field=models.JSONField(blank=True, default=dict, help_text="Sample context data for testing/preview. Example: {'order': {'id': 123, 'total': 999}, 'user': {'name': 'John'}}", verbose_name='Sample Context'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='sms_template',
            field=models.CharField(blank=True, help_text='Template for SMS (max 160 chars recommended)', max_length=160, verbose_name='SMS Template'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags for filtering and organization. Example: ['transactional', 'high-priority']", verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='throttle_config',
            field=models.JSONField(blank=True, default=dict, help_text="Rate limiting config. Example: {'max_per_user_per_day': 3, 'min_interval_minutes': 60}", verbose_name='Throttle Configuration'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='tracking_enabled',
            field=models.BooleanField(default=True, help_text='Whether to track opens, clicks, and conversions for this template', verbose_name='Enable Tracking'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_templates', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Template version for A/B testing and rollbacks', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='whatsapp_template',
            field=models.TextField(blank=True, help_text='Template for WhatsApp message', verbose_name='WhatsApp Template'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body_template',
            field=models.TextField(help_text='Django template for notification body. Supports {{ variables }} and {% tags %}', verbose_name='Body Template'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='category',
            field=models.CharField(db_index=True, help_text="Grouping category (e.g., 'orders', 'payments', 'users', 'system')", max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='default_priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Default Priority'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='email_body_template',
            field=models.TextField(blank=True, help_text='Django template for email body (can include HTML)', verbose_name='Email Body Template'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='email_subject_template',
            field=models.CharField(blank=True, help_text='Template for email subject line', max_length=255, verbose_name='Email Subject Template'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='enabled_channels',
            field=models.JSONField(default=list, help_text="List of channels this template supports. Example: ['push', 'email', 'sms']", verbose_name='Enabled Channels'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='locale',
            field=models.CharField(db_index=True, default='en', help_text="Language/locale code (e.g., 'en', 'hi', 'en-US')", max_length=10, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(db_index=True, help_text="Unique identifier (e.g., 'order_confirmed', 'payment_failed')", max_length=100, unique=True, verbose_name='Template Name'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', help_text='Visual type for UI rendering (color, icon, etc.)', max_length=10, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='title_template',
            field=models.CharField(help_text="Django template for notification title. Example: 'Order #{{ order.id }} confirmed'", max_length=255, verbose_name='Title Template'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['category', 'name'], name='tbl_notific_categor_a81f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['locale', 'is_active'], name='tbl_notific_locale_e8bb93_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['category', 'is_active'], name='tbl_notific_categor_3cfea6_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('name', 'locale'), name='unique_template_per_locale'),
        ),
        migrations.AddField(
            model_name='deeplink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deep_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deeplink',
            index=models.Index(fields=['user', 'status', 'created_at'], name='deep_links_user_id_4fb43b_idx'),
        ),
        migrations.AddIndex(
            model_name='deeplink',
            index=models.Index(fields=['module', 'status'], name='deep_links_module_0d4e41_idx'),
        ),
        migrations.AddIndex(
            model_name='deeplink',
            index=models.Index(fields=['expires_at', 'status'], name='deep_links_expires_a19a06_idx'),
        ),
    ]
