# Generated by Django 4.2 on 2025-06-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_appnotification_delivery_attempted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='allowed_email',
            field=models.BooleanField(default=False, help_text='Used to handle if email notification allowed or not.', verbose_name='Allowed Email'),
        ),
    ]
