# Generated by Django 4.2 on 2025-10-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notificationdelivery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTrackMppCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_code', models.CharField(max_length=200, verbose_name='Mpp Collection Code')),
                ('is_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notification_track',
            },
        ),
    ]
