# Generated by Django 4.2 on 2025-10-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notificationtrackmppcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='locale',
            field=models.CharField(default='en', help_text="Locale (e.g., 'hi', 'en')", max_length=50, verbose_name='Locale'),
        ),
    ]
