# Generated by Django 4.2 on 2025-10-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notificationtemplate_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partialy_sent', 'Partially Sent')], default='pending', help_text='Tracks whether the notification was successfully delivered.', max_length=20, verbose_name='Delivery Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partialy_sent', 'Partially Sent')], db_index=True, default='pending', help_text='Current status of the notification (pending, sent, delivered, failed).', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partialy_sent', 'Partially Sent')], default='pending', help_text='Current status of the delivery attempt.', max_length=20, verbose_name='Delivery Status'),
        ),
    ]
