# Generated by Django 4.2 on 2025-10-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_appnotification_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='custom_key',
            field=models.CharField(blank=True, help_text='Optional key used for grouping or client-side logic.', max_length=100, null=True, verbose_name='Custom Key'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_subroute',
            field=models.BooleanField(default=False, help_text='Indicates if the route is a sub-path or detail view.', verbose_name='Is Subroute'),
        ),
    ]
